[tools]
etcd = "latest"

[tasks.dev]
description = "Cargo run"
run = "cargo run"

[tasks.build]
description = "Cargo build dev"
run = "cargo build"

[tasks.release]
description = "Cargo build release"
run = "cargo build --release"

[tasks.serve]
description = "Serve using trunk"
run = "trunk serve"

[tasks.check]
description = "Runs the included script to check all builds"
file = "./check.sh"